---
- name: Configure basic system settings
  hosts: 
    - webserver
    - database
  sudo: yes
  vars:
    motd: "Hello tekkisessio!"

  tasks:
    - include: tasks/users.yml
    - name: Set message of the day
      copy:
        content: "{{motd}}"
        dest: /etc/motd

- name: Configure database server
  hosts: database
  sudo: yes

  roles:
    - roles/andperez.mongodb