- name: Install nginx
  yum: 
    name: nginx
    state: present

- name: Configure nginx
  template: src=templates/server.conf.j2 dest=/etc/nginx/conf.d/server.conf
  notify: restart nginx

- name: Start nginx
  service: name=nginx state=started