- name: Install nginx
  yum: 
    name: nginx
    state: present

- name: Configure nginx
  template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Start nginx
  service: name=nginx state=started