---
- include_vars: node12.yml
  when: nodejs_version.startswith("0.12.")
- include_vars: node10.yml
  when: nodejs_version.startswith("0.10.")
- fail: msg="supported nodejs_version are 0.10 or 0.12"
  when: nodejs_source_pub is not defined
