---
- name: Configure basic system settings
  hosts: 
    - webserver
    - database
  sudo: yes
  vars:
    motd: "Hello tekkisessio!"

  tasks:
    - include: tasks/users.yml
    - name: Set message of the day
      copy:
        content: "{{motd}}"
        dest: /etc/motd
    - include: tasks/epel.yml

# - name: Configure database server
#   hosts: database
#   sudo: yes

#   roles:
#     - roles/andperez.mongodb


- name: Configure web server
  hosts: webserver
  sudo: yes

  roles:
  - role: roles/advertine.nodejs
    nodejs_version: "0.12.2"

  tasks:
    - include: tasks/nginx.yml
    # - name: Start litti
    #   shell: command=cd /vagrant/litti && npm install && MONGOLAB_URI="mongodb://192.168.50.3:27017" npm start sudo=yes

  handlers:
    - include: handlers/main.yml